### ISSUE TITLE
Importer limited to max 8 in each field

### ISSUE THREAD

**Issue by gingerbeardman** [hpcodecraft/sleekspriter#1]
This is nice!

I am trying to import a sprite sheet of 32x32px sprites

32 wide
3 high

size 1024x96px

but the importer only allows maximum number of 8 in each field?

it would be nice here if i could just type the size of the sprite: 32, 32

or if it could be gleaned from the filename, ending `-table-32-32.png`

![Screen shot 2020-06-18 at 01 18 52](https://user-images.githubusercontent.com/49612/84963581-ae905680-b101-11ea-884f-aec1e481d7ea.png)

**Comment by hpcodecraft** [comment]
Thanks for the hint!

I think I limited it so that the clickable frame previews don't become too tiny.
Making the frame size input fields should be possible in any case, I guess

**Comment by gingerbeardman** [comment]
Either way, thanks!

I am coming from Piskel - which is great in a number of ways, but annoys me with many user interface quirks - so am excited about your app!

**Comment by hpcodecraft** [comment]
Thank you for your feedback! I'll check the other issues now - and update here as soon as something changed, of course

**Comment by gingerbeardman** [comment]
Thanks for the update! 

However I get this error on running it:

<img width="420" alt="Screen shot 2020-11-03 at 10 25 54" src="https://user-images.githubusercontent.com/49612/97974115-0b459280-1dbf-11eb-9f3d-513fcf791d06.png">

**Comment by hpcodecraft** [comment]
Yes, sorry about that - I had added automatic updates but found out that this needs a Apple Developer Membership, which costs an annually fee..

I've removed it again for Mac OS in the 0.3.4. release, which should launch. Sorry for the mistake!

**Comment by hpcodecraft** [comment]
Btw, did the update solve the issue with your 32x3 frames sprite? If so, feel free to close the issue or let me know if I can close it. Thanks!

**Comment by gingerbeardman** [comment]
Yes, it did, thanks!

I've gone bigger and am using 32x9: https://twitter.com/gingerbeardman/status/1309898809565229056
