### ISSUE TITLE
Apple silicon support

### ISSUE THREAD

**Issue by gingerbeardman** [hpcodecraft/sleekspriter#11]
It would be great if the macOS version was a Universal binary, able to run on Intel and Apple silicon CPUs.

**Comment by hpcodecraft** [comment]
Very valid point, I didn't consider this yet - I'll check what is necessary to make a universal binary!

**Comment by hpcodecraft** [comment]
@gingerbeardman Just a quick update: I didn't forget this 😅 I got the build, but it seems Apple Silicon Macs do not allow to run unsigned apps anymore, so I'm now diving into the code signing rabbit hole. I'll try to get this done asap!

Also, I will create a separate build for Silicon -  Universal Binaries are basically just both apps bundled into one, so their disk size is doubled without any significant advantage.

**Comment by gingerbeardman** [comment]
Don't worry I finally succumbed and installed Rosetta 2 to run Intel apps.

Cheers!
