### ISSUE TITLE
Option to use standard cursor rather than crosshair

### ISSUE THREAD

**Issue by gingerbeardman** [hpcodecraft/sleekspriter#2]
I can't see the cross hair very well.

It would be nice to be able to use standard cursor rather than crosshair.

![Screen shot 2020-06-22 at 10 46 05](https://user-images.githubusercontent.com/49612/85273552-a6277b00-b475-11ea-826e-c2f09a5a71cb.png)

**Comment by hpcodecraft** [comment]
Thanks, I'll make the color configurable and add an option to use the default OS cursor.

**Comment by hpcodecraft** [comment]
I just published 0.2.41 which introduces a settings panel and allows these settings :)

**Comment by hpcodecraft** [comment]
Please let me know what you think :)

**Comment by gingerbeardman** [comment]
Settings work great, thanks.
