### ISSUE TITLE
Expose more items in menus

### ISSUE THREAD

**Issue by gingerbeardman** [hpcodecraft/sleekspriter#3]
I like to map my own shortcuts using macOS System Preferences, but they require menu items.

It would be great if you could expose all tools in a menu, and also the various zoom options.

Thanks!

**Comment by hpcodecraft** [comment]
Hey! I finally found some time and reworked the whole hotkey handling. The zoom options and all tools have their own items in 0.3.5 now :)

**Comment by gingerbeardman** [comment]
Woohoo! I'll download.

**Comment by gingerbeardman** [comment]
Thank you, closing this one.
