### ISSUE TITLE
Menu items to have unique labels

### ISSUE THREAD

**Issue by gingerbeardman** [hpcodecraft/sleekspriter#4]
It would be great if menu items could be uniquely named for macOS shortcut mapping and accessibility reasons. 

eg. Rotate/Flip in Edit/Frame menus

![Screen shot 2020-06-22 at 10 55 52](https://user-images.githubusercontent.com/49612/85274551-ff43de80-b476-11ea-9a55-d5f352dc446c.png)

**Comment by hpcodecraft** [comment]
Hello again, sorry for the silence - my day job currently takes all my time. This one sounds like a low hanging fruit though :D Can you elaborate a bit on what you mean? I'm not using this MacOS feature.

Would renaming the items to e.g. "Flip frame horizontal" and "Flip horizontal" achieve your goal?

**Comment by gingerbeardman** [comment]
Yes, exactly!

Thanks

**Comment by hpcodecraft** [comment]
Hey, the latest release should implement this. Please let me know if it solves your issue.

**Comment by gingerbeardman** [comment]
Indeed it does! Thank you
