### ISSUE TITLE
Grid colour/visibility to be configurable

### ISSUE THREAD

**Issue by gingerbeardman** [hpcodecraft/sleekspriter#5]
I also think the grid is too dark, could its colour be configurable or allow it to be hidden?

Thanks

![Screen shot 2020-06-22 at 10 46 05](https://user-images.githubusercontent.com/49612/85273552-a6277b00-b475-11ea-826e-c2f09a5a71cb.png)

**Comment by hpcodecraft** [comment]
You can hide it by pressing "g" or the button on the bottom right of the drawing area.

I have plans to add a settings panel though which will include an option to choose a different color and (now) an option to hide it by default.

**Comment by gingerbeardman** [comment]
Thanks

**Comment by hpcodecraft** [comment]
I just published 0.2.41 which introduces a settings panel and allows these settings :)

**Comment by gingerbeardman** [comment]
Super, thanks
