### ISSUE TITLE
More menus/commands/keyboard shortcuts

### ISSUE THREAD

**Issue by gingerbeardman** [hpcodecraft/sleekspriter#7]
Menu and menu items are a good way of exposing all features of an app. Moreso with SleekSpriter because the interface is fairly non-standard. Doing so makes the app more accessible.

Take a look at [Acorn](https://flyingmeat.com/acorn/) (macOS only) or Photoshop (Win/macOS) for examples of good accessibility.

## menus/commands/keyboard shortcuts
- next/previous frame
- nudge canvas (cursors and modifier)

## menu
- onion skin toggle (<kbd>o</kbd> key)
- grid toggle (<kbd>g</kbd> key)

etc.

apologies if any of these exist and i have not found them, or the docs that describe them!

**Comment by hpcodecraft** [comment]
Hello, please have a look at the 0.3.5 release - everything that has a keyboard shortcut now has it's own menu item.

**Comment by gingerbeardman** [comment]
Just checking 0.3.8

still missing
- onion skin toggle (o key)

but otherwise much improved, thanks!

**Comment by hpcodecraft** [comment]
Huh, that one should be there - the last item in the "View" menu, "Toggle Onion Panel"

**Comment by gingerbeardman** [comment]
Ah, I had not loaded an animation.

I see it now.
