### ISSUE TITLE
Closing main window, File > New no longer works

### ISSUE THREAD

**Issue by gingerbeardman** [hpcodecraft/sleekspriter#8]
## Steps

1. Run SleekSpriter
2. Close main window
3. Choose File < New

## Expected

- new file prompt

## Actual 

- Nothing happens

**Comment by hpcodecraft** [comment]
Thanks for the report, I'll look into it - this is the Mac OS desktop app, right?

**Comment by gingerbeardman** [comment]
Yes indeed

**Comment by hpcodecraft** [comment]
I have looked into it, and I'm pretty sure this never worked. You can close the file via the Close menu item, but when you close the main window the app is lost.. I will try to fix it!

**Comment by hpcodecraft** [comment]
Just a small update: When you click on the dock icon after closing the main window, it will be restored and File -> New works again. Not a fix (yet), but a workaround at least :)

**Comment by gingerbeardman** [comment]
Cool! Very helpful.

**Comment by hpcodecraft** [comment]
It turns out this is a lot trickier than I thought with the current setup - I've tried a lot of things but nothing worked as I expected. For now, I've changed the closing behaviour so that the whole app closes when the main window is closed.

**Comment by gingerbeardman** [comment]
Works for me, thanks.
