### ISSUE TITLE
Add frames to image with 1 frame

### ISSUE THREAD

**Issue by gingerbeardman** [hpcodecraft/sleekspriter#9]
An image with 1 frame disables the frame section of the app.

This makes it difficult/impossible to add a new frame.

So I can't load a single image and then work it into an animation.

Apologies if I am missing something!

**Comment by hpcodecraft** [comment]
You're right, currently you have to choose the amount of frames when you create it and it can't be changed later. I'll think of a way to change this!

As a workaround, you can try this for the moment:
1. Open the saved .pixels file in a text editor
2. Change the part `"frames":[1,1]` to the number of frames you want. The first number is the amount of columns, the second the amount of rows.
3. Save the file and re-open it in SleekSpriter.

**Comment by hpcodecraft** [comment]
0.3.11 adds a new menu item & modal window to convert single frame images to spritesheets :)
Thanks for pointing this out!
